# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(email:"pgrand@miaundes.cl", password:"123123")
Ingredient.create(name:"peperoni")
Ingredient.create(name:"tomato")
Ingredient.create(name:"pineapple")
Ingredient.create(name:"cheese")
Ingredient.create(name:"chicken bbq")
Ingredient.create(name:"meat")
Crust.create(size:"regular", price:4000)
Crust.create(size:"thin", price:2500)
Recipe.create(price:4500)
Recipe.create(price:4000)
Recipe.create(price:5000)
Recipe.create(price:5500)
RecipeIngredient.create(recipe_id:1, ingredient_id:1)
RecipeIngredient.create(recipe_id:1, ingredient_id:3)
RecipeIngredient.create(recipe_id:1, ingredient_id:4)
RecipeIngredient.create(recipe_id:2, ingredient_id:1)
RecipeIngredient.create(recipe_id:2, ingredient_id:2)
RecipeIngredient.create(recipe_id:2, ingredient_id:3)
RecipeIngredient.create(recipe_id:2, ingredient_id:5)
RecipeIngredient.create(recipe_id:3, ingredient_id:6)
RecipeIngredient.create(recipe_id:3, ingredient_id:2)
RecipeIngredient.create(recipe_id:3, ingredient_id:1)
RecipeIngredient.create(recipe_id:4, ingredient_id:6)
RecipeIngredient.create(recipe_id:4, ingredient_id:2)
RecipeIngredient.create(recipe_id:4, ingredient_id:1)
Pizza.create(name:"napoles",recipe_id:1, crust_id:1)
Pizza.create(name:"italian",recipe_id:1, crust_id:2)
Pizza.create(name:"hawaian",recipe_id:2, crust_id:1)
Pizza.create(name:"chilean",recipe_id:2, crust_id:2)
Pizza.create(name:"perubian",recipe_id:3, crust_id:1)
Pizza.create(name:"argentinian",recipe_id:3, crust_id:2)
Pizza.create(name:"space is the place",recipe_id:4, crust_id:1)
Pizza.create(name:"flargo", recipe_id:4, crust_id:2)
Photo.create(pizza_id:1, image: File.new('app/assets/images/pizza0.jpg', 'r'))
Photo.create(pizza_id:2, image: File.new('app/assets/images/pizza0.jpg', 'r'))
Photo.create(pizza_id:3, image: File.new('app/assets/images/pizza1.jpg', 'r'))
Photo.create(pizza_id:4, image: File.new('app/assets/images/pizza1.jpg', 'r'))
Photo.create(pizza_id:5, image: File.new('app/assets/images/pizza2.jpg', 'r'))
Photo.create(pizza_id:6, image: File.new('app/assets/images/pizza2.jpg', 'r'))
Photo.create(pizza_id:7, image: File.new('app/assets/images/pizza0.jpg', 'r'))
Photo.create(pizza_id:8, image: File.new('app/assets/images/pizza1.jpg', 'r'))

